// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN3bM5NP5GHEiT0P65DnChlPAaNtLjfbk',
    appId: '1:789505071184:web:0320385b63cf5ef391d955',
    messagingSenderId: '789505071184',
    projectId: 'gemilife-1ce43',
    authDomain: 'gemilife-1ce43.firebaseapp.com',
    storageBucket: 'gemilife-1ce43.appspot.com',
    measurementId: 'G-9WYZ89REQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi9cCuZmIefcbJ5g1PB3Zj8zOmGsNe9FI',
    appId: '1:789505071184:android:939a3c28178fdcb791d955',
    messagingSenderId: '789505071184',
    projectId: 'gemilife-1ce43',
    storageBucket: 'gemilife-1ce43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi-dLdqRDuiK6-R_mQcT2Sriq-ldNxodA',
    appId: '1:789505071184:ios:90c72e9e2d54628591d955',
    messagingSenderId: '789505071184',
    projectId: 'gemilife-1ce43',
    storageBucket: 'gemilife-1ce43.appspot.com',
    iosBundleId: 'com.example.gemilife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi-dLdqRDuiK6-R_mQcT2Sriq-ldNxodA',
    appId: '1:789505071184:ios:01b1079d3fa4da5791d955',
    messagingSenderId: '789505071184',
    projectId: 'gemilife-1ce43',
    storageBucket: 'gemilife-1ce43.appspot.com',
    iosBundleId: 'com.example.gemilife.RunnerTests',
  );
}
